language: node_js
node_js:
- '0.10'
services:
- mongodb
env:
  global:
  - NODE_ENV=travisci
  - BUILD_DIR=`pwd`/zpratt
before_script:
- npm install -g grunt-cli
- npm install -g bower
- bower install
notifications:
  slack: stopverf:x19pw3uwpsTdXi0KMHzKZ1M4
deploy:
  provider: nodejitsu
  user: patrickhopman
  api_key:
    secure: GWmivzcNMGoaESiYbJiYXIVVoyz5CX1Fc9b+gUSnORNIvBWEGRq0BdbAiO+xuUjz5KKu8JBsFNXnpYeAMsau/x7rLcbxTHdlwOXOsOAH9927+6j2HWG6PSidp6reQfW/pI8QU0uxHS4zKnYnQkYQbJGKd8HAy0eQSMdWicD0HTo=
  on:
    repo: patrickhopman/Voorraadbeheer
